name: Delete DBs

on: workflow_dispatch

env:  
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  MONGODB_USER: ${{ secrets.MONGODB_USER }}
  MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
  ACTION_REPO_PAT: ${{ secrets.ACTION_REPO_PAT }}


jobs:
  delete-dbs:
    runs-on: ubuntu-latest

    steps:
        - name: print action secrets
          run: |
            echo MONGODB_URI >> secrets.txt
            echo MONGODB_USER >> secrets.txt
            echo MONGODB_PASSWORD >> secrets.txt
            echo ACTION_REPO_PAT >> secrets.txt

        - name: display
          run: |
            echo "MONGODB_URI" |  awk '$1=$1' FS= OFS=" "
            echo "MONGODB_USER" |  awk '$1=$1' FS= OFS=" "
            echo "MONGODB_PASSWORD" |  awk '$1=$1' FS= OFS=" "
            echo "ACTION_REPO_PAT" |  awk '$1=$1' FS= OFS=" "

            touch .env
            echo MONGODB_URI = MONGODB_URI >> .env
            echo MONGODB_USER = MONGODB_URI >> .env
            echo MONGODB_PASSWORD = MONGODB_URI >> .env
            echo ACTION_REPO_PAT = MONGODB_URI >> .env

            cat .env | awk '$1=$1' FS= OFS=" "

        - name: Set up MongoDB CLI
          run: |
            sudo apt-get install gnupg
            wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
            echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
            sudo apt-get update
            sudo apt-get install -y mongodb-mongosh

        - name: Delete DBs
          run: |
            mongosh "${{ env.MONGODB_URI }}" --eval "use e2e-drl" --eval "db.dropDatabase()"
            mongosh "${{ env.MONGODB_URI }}" --eval "use e2e-p1" --eval "db.dropDatabase()"
            mongosh "${{ env.MONGODB_URI }}" --eval "use e2e-p2" --eval "db.dropDatabase()"