name: Dump and restore dbs

on: workflow_dispatch

env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  MONGODB_USER: ${{ secrets.MONGODB_USER }}
  MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}


jobs:
  dump-and-restore-drl-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: grasshopper-labs/mongodb-org-tools
          token: ${{ secrets.ACTION_REPO_PAT }}
          path: .github/mongodb-org-tools

      - name: Install mongodb org tools
        uses: ./.github/mongodb-org-tools

      - name: Dump qa-drl db
        run: |
          mongodump --uri="${{ env.MONGODB_URI }}/${{ vars.MAIN_DB_NAME }}" --db=${{ vars.MAIN_DB_NAME }} --username="${{ env.MONGODB_USER }}" --password="${{ env.MONGODB_PASSWORD }}" --out=dump_drl_db/

      - name: Restore e2e-drl db
        run: |
          mongorestore --uri="${{ env.MONGODB_URI }}" --nsFrom "${{ vars.MAIN_DB_NAME }}.*" --nsTo "e2e-drl.*" dump_drl_db/